language: node_js
node_js:
  - "6"
  - "10"

sudo: false

notifications:
  email:
    - services@wikimedia.org

addons:
  apt:
    packages:
    - openjdk-8-jre-headless

env:
  - CASSANDRA_VERSION=3.11.2

before_install:
  - wget https://archive.apache.org/dist/cassandra/${CASSANDRA_VERSION}/apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz -P ../
  - tar -xzf ../apache-cassandra-${CASSANDRA_VERSION}-bin.tar.gz -C ../
  - export JAVA_HOME="/usr/lib/jvm/java-8-openjdk-amd64"
  - mkdir -p ../apache-cassandra-${CASSANDRA_VERSION}/logs
  - echo "-Xms512m" >> ../apache-cassandra-${CASSANDRA_VERSION}/conf/jvm.options
  - echo "-Xmx1g" >> ../apache-cassandra-${CASSANDRA_VERSION}/conf/jvm.options
  - sed -i -e 's/^-XX:+UseNUMA/#-XX:+UseNUMA/' ../apache-cassandra-${CASSANDRA_VERSION}/conf/jvm.options
  - bash ../apache-cassandra-${CASSANDRA_VERSION}/bin/cassandra > /dev/null

script: npm run-script coverage && (npm run-script coveralls || exit 0)
